title: Muhammad Rizqi (Kingki19)
avatar: /assets/img/circle_logo.png
round-avatar: true
description: >
  <p>An enthusiastic people who learn about data science. Capable of doing data manipulation, modelling, data visualization using Python. Have experience in conducting Natural Language Processing (NLP) and Time-Series Analysis.</p>
  <p>Currently, I'm really into diving into time series analysis and quantitative analysis. These areas have my main attention, but I'm also keeping my options open and still exploring other possibilities. I'm excited about taking on new challenges and always on the lookout for fresh opportunities in the ever-evolving field of data science.</p>
show_downloads: false
theme: jekyll-theme-minimal
url: "https://kingki19.github.io"
author: Muhammad Rizqi
email: mrizqi6061@gmail.com
