title: Muhammad Rizqi (Kingki19)
logo: /assets/img/circle_logo.png
description: >
  <p>An enthusiastic people who learn about data science. Capable of doing data manipulation, modelling, data visualization using Python. Have experience in conducting Natural Language Processing (NLP) and Time-Series Analysis.</p>
  <p>Connect with me:</p>
  <ul>
    <li> 
      <a href="https://github.com/Kingki19">
        <img src="https://img.shields.io/badge/GitHub-Kingki19-blue?logo=github" alt="GitHub">
      </a>
    </li>
  </ul>
show_downloads: true
theme: jekyll-theme-minimal
url: "https://kingki19.github.io"
author: Muhammad Rizqi
email: mrizqi6061@gmail.com
