title: Muhammad Rizqi (Kingki19)
logo: /assets/img/circle_logo.png
description: >
  <p>An enthusiastic people who learn about data science. Capable of doing data manipulation, modelling, data visualization using Python. Have experience in conducting Natural Language Processing (NLP) and Time-Series Analysis.</p>
  <br></br>
  <p>Connect with me:</p>
show_downloads: true
theme: jekyll-theme-minimal
url: "https://kingki19.github.io"
author: Muhammad Rizqi
email: mrizqi6061@gmail.com
social:
  - title: GitHub
    url: https://github.com/kingki19
  - title: Kaggle
    url: https://www.kaggle.com/kingki19
