title: Muhammad Rizqi (Kingki19)
logo: /assets/img/circle_logo.png
description: >
  <p>An enthusiastic people who learn about data science. Have experiences in analyzing data using Python. Currently, I'm really into diving into time series analysis and quantitative analysis.</p>
show_downloads: false
theme: jekyll-theme-minimal
url: "https://kingki19.github.io"
author: Muhammad Rizqi
email: mrizqi6061@gmail.com
